apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage-demo
  description: Python app that displays time - named backstage-demo
  annotations:
    github.com/project-slug: hsenagr/backstage-demo
    backstage.io/techdocs-ref: dir:.
spec:
  type: service
  owner: development
  lifecycle: experimental
