site_name: 'backstage-demo'
site_description: 'Main documentation for the backstage-demo'
repo_url: https://github.com/hsenagr/backstage-demo
edit_uri: edit/main/docs

plugins:
  - techdocs-core

# For sidebar navigation on https://backstage.io/, see `microsite/sidebars.json`
nav:
  - Overview:
      - Getting started: 'docs/index.md'
